/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectCommand
 */
export interface CreateProjectCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectCommand
     */
    name?: string | null;
}

export function CreateProjectCommandFromJSON(json: any): CreateProjectCommand {
    return CreateProjectCommandFromJSONTyped(json, false);
}

export function CreateProjectCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CreateProjectCommandToJSON(value?: CreateProjectCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

