/* tslint:disable */
/* eslint-disable */
/**
 * CleanArchitecture.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ToDoItemDto,
    ToDoItemDtoFromJSON,
    ToDoItemDtoFromJSONTyped,
    ToDoItemDtoToJSON,
} from './ToDoItemDto';

/**
 * 
 * @export
 * @interface ProjectDto
 */
export interface ProjectDto {
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    name?: string | null;
    /**
     * 
     * @type {Array<ToDoItemDto>}
     * @memberof ProjectDto
     */
    items?: Array<ToDoItemDto> | null;
}

export function ProjectDtoFromJSON(json: any): ProjectDto {
    return ProjectDtoFromJSONTyped(json, false);
}

export function ProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(ToDoItemDtoFromJSON)),
    };
}

export function ProjectDtoToJSON(value?: ProjectDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(ToDoItemDtoToJSON)),
    };
}

